name: homelab
services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    ports:
      - "3000:3000/tcp"
      - "53:53/tcp"
      - "53:53/udp"
      - "853:853/tcp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
    networks:
      - proxy
    restart: unless-stopped
    volumes:
      - ./data/adguard:/opt/adguardhome/work
      - ./config/adguard:/opt/adguardhome/conf
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguard.entryPoints=websecure
      - traefik.http.routers.adguard.rule=Host(`adguard.${DOMAIN}`)
      - traefik.http.services.adguard.loadbalancer.server.port=80
  ddns-updater:
    image: qmcgaw/ddns-updater:v2.8
    container_name: ddns-updater
    environment:
      CONFIG: |
        {
          "settings": [
            {
              "provider": "desec",
              "domain": "${DOMAIN}",
              "token": "${DESEC_TOKEN}",
              "ip_version": "ipv4"
            }
          ]
        }
    labels:
      - traefik.enable=true
      - traefik.http.routers.ddns-updater.entryPoints=websecure
      - traefik.http.routers.ddns-updater.rule=Host(`ddns-updater.${DOMAIN}`)
    networks:
      - proxy
    restart: unless-stopped
  authelia:
    image: authelia/authelia
    container_name: authelia
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - AUTHELIA_JWT_SECRET=${AUTHELIA_JWT_SECRET}
      - AUTHELIA_SESSION_SECRET=${AUTHELIA_SESSION_SECRET}
      - AUTHELIA_STORAGE_ENCRYPTION_KEY=${AUTHELIA_STORAGE_ENCRYPTION_KEY}
    labels:
      - traefik.enable=true
      - traefik.http.routers.authelia.entryPoints=websecure
      - traefik.http.routers.authelia.rule=Host(`auth.${DOMAIN}`)

      - traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/authz/forward-auth
      - traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true
      - traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Email,Remote-Nam
    restart: unless-stopped
    volumes:
      - ./config/authelia.yml:/config/configuration.yml:ro
      - ./data/authelia:/config/
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - "443:443"
      - "8080:8080"
    dns:
      - 1.1.1.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./data/traefik/certs/:/var/traefik/certs/:rw
    environment:
      - DESEC_TOKEN=${DESEC_TOKEN}
      - DESEC_POLLING_INTERVAL=75
      - DESEC_PROPAGATION_TIMEOUT=300
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entryPoints=websecure
      - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.traefik.service=api@internal

    restart: unless-stopped
networks:
  proxy:
    name: proxy
    driver: bridge
