ansible_host: localhost
ansible_connection: local
user: core

network_interfaces:
  - name: eth0
    address: 192.168.1.11/24
    gateway: 192.168.1.254
    dns:
      - 1.1.1.1
      - 8.8.8.8

storage:
  mergerfs_opts: "defaults,nonempty,allow_other,use_ino,cache.files=partial,dropcacheonclose=true,category.create=epmfs"
  pool_mount: /mnt/storage
  disks:
    - device: /dev/sdb
      label: disk1
      mount: /mnt/disk1
    - device: /dev/sdc
      label: disk2
      mount: /mnt/disk2
