---
- name: Setup core machine
  hosts: core
  gather_facts: true
  vars:
    services_dir: "{{ (playbook_dir + '/../services') | realpath }}"
    remote_services_dir: "{{ ansible_facts.env.HOME }}"
    shared_env_content: "{{ lookup('community.sops.sops', services_dir + '/env.sops') }}"
    domain: "{{ shared_env_content | regex_search('DOMAIN=(.*)', '\\1') | first }}"
    email: "{{ shared_env_content | regex_search('EMAIL=(.*)', '\\1') | first }}"
  handlers:
    - name: restart systemd-resolved
      systemd:
        name: systemd-resolved
        state: restarted
  tasks:
    - name: Sync files
      ansible.builtin.import_tasks: tasks/sync_files.yml
      tags:
        - sync
        - deploy
    - name: Deploy all services
      community.docker.docker_compose_v2:
        project_src: "{{ remote_services_dir }}/services"
        project_name: homelab
        state: present
        remove_orphans: true
        env_files:
          - env
      tags:
        - deploy
