---
- name: Setup core machine
  hosts: core
  gather_facts: true
  vars:
    repo_services_dir: "{{ (playbook_dir + '/../services') | realpath }}"
    remote_dir: "{{ ansible_facts.env.HOME }}/server"
    shared_env_content: "{{ lookup('community.sops.sops', repo_services_dir + '/env.sops') }}"
    domain: "{{ shared_env_content | regex_search('DOMAIN=(.*)', '\\1') | first }}"
    email: "{{ shared_env_content | regex_search('EMAIL=(.*)', '\\1') | first }}"
  tasks:
    - name: Sync files
      ansible.builtin.import_tasks: tasks/sync_files.yml
      tags:
        - sync
        - deploy
    - name: Deploy all services
      community.docker.docker_compose_v2:
        project_src: "{{ remote_dir }}"
        project_name: homelab
        state: present
        remove_orphans: true
        env_files:
          - env
      tags:
        - deploy
