services:
  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    restart: unless-stopped
    volumes:
      - ./data/prowlarr:/config
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 9696:9696
    labels:
      - traefik.enable=true
      - traefik.http.routers.prowlarr.entryPoints=websecure
      - traefik.http.routers.prowlarr.rule=Host(`prowlarr.${DOMAIN}`)
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    restart: unless-stopped
    volumes:
      - ./data/lidarr:/config
      - /mnt/storage/music:/storage
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
    labels:
      - traefik.enable=true
      - traefik.http.routers.lidarr.entryPoints=websecure
      - traefik.http.routers.lidarr.rule=Host(`lidarr.${DOMAIN}`)
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8086
      - TORRENTING_PORT=6881
    volumes:
      - ./data/:/config
      - /mnt/storage/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
    stop_grace_period: "10s"
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.qbittorrent.entryPoints=websecure
      - traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.${DOMAIN}`)
      - traefik.http.services.qbittorrent.loadbalancer.server.port=8086
    networks:
      - proxy
