services:
  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    restart: always
    volumes:
      - ./data/prowlarr:/config
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 9696:9696
    labels:
      - traefik.enable=true
      - traefik.http.routers.prowlarr.entryPoints=websecure
      - traefik.http.routers.prowlarr.rule=Host(`prowlarr.${DOMAIN}`)
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    restart: always
    volumes:
      - ./data/lidarr:/config
      - /mnt/storage/music:/storage
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 8686:8686
    labels:
      - traefik.enable=true
      - traefik.http.routers.lidarr.entryPoints=websecure
      - traefik.http.routers.lidarr.rule=Host(`lidarr.${DOMAIN}`)
