---
- name: Setup core machine
  hosts: core
  gather_facts: true
  vars:
    repo_services_dir: "{{ (playbook_dir + '/../services') | realpath }}"
    remote_dir: "{{ ansible_facts.env.HOME }}/homelab-core"
  tasks:
    - name: Load encrypted variables
      ansible.builtin.set_fact:
        "{{ item.key }}": "{{ item.value }}"
      loop: >-
        {{
          dict(
            lookup('community.sops.sops', repo_services_dir + '/env.sops').splitlines()
            | reject('match', '^\s*#|^\s*$')
            | map('split', '=', 1)
            | map('map', 'trim')
          ) | dict2items
        }}
      no_log: true
      tags:
        - always

    - name: Sync files
      ansible.builtin.import_tasks: tasks/sync_files.yml
      tags:
        - sync

    - name: Deploy all services
      community.docker.docker_compose_v2:
        project_src: "{{ remote_dir }}"
        project_name: homelab
        state: present
        remove_orphans: true
        env_files:
          - env
      tags:
        - deploy

    - name: Configure Prowlarr
      ansible.builtin.import_tasks: tasks/media/prowlarr.yml
      tags:
        - deploy
        - prowlarr
