---
- name: Extract Hosts from SOPS
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Dynamically add Proxmox hosts
      add_host:
        name: "{{ item.key }}"
        groups: proxmox_nodes
        ansible_user: root
        cluster_name: "{{ item.key }}"
        ansible_host: "{{ item.value.ip }}"
      loop: "{{ _secrets['clusters_access'] | dict2items }}"
      when: item.value.ip is defined
      no_log: true
- name: Setup Proxmox
  hosts: proxmox_nodes
  gather_facts: true
  vars:
    pve_repository_line: "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription"
    pve_remove_subscription_nag: true
    pve_reboot_on_kernel_update: true
    pve_pcie_passthrough_enabled: true

    pve_iommu_passthrough_mode: true
    pve_mediated_devices_enabled: true
  roles:
    - role: lae.proxmox
